import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

// Social mockups are shared at 1080p-class sizes, so a 1920x1080 upload is the
// heaviest realistic source (also the Toolcraft media-fixture minimum). Larger
// source images are not a target use case for this tool.
const heavyMedia = { height: 1080, width: 1920 };

const heavyMediaLoadProfile = {
  hardLimit: heavyMedia,
  metric: "media-area",
  smoothTarget: heavyMedia,
  smoothTargetRatio: 1,
  target: "frames.images",
  userFacingRange: "fully-guaranteed",
} as const;

function customLoadProfile(target: string, value: unknown) {
  return {
    hardLimit: value,
    metric: "custom",
    smoothTarget: value,
    smoothTargetRatio: 1,
    target,
    userFacingRange: "fully-guaranteed",
  } as const;
}

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-drag",
        invalidates: ["composite"],
        mustNotInvalidate: ["decode"],
        targets: ["frame.scale", "frame.cornerRadius", "background.blur"],
      },
      {
        interaction: "control-change",
        invalidates: ["composite"],
        mustNotInvalidate: ["decode"],
        targets: [
          "frames.transition",
          "frame.shadow",
          "background.mode",
          "background.color",
          "background.gradient",
          "export.includeBackground",
        ],
      },
      {
        interaction: "media-import",
        invalidates: ["decode", "composite"],
        targets: ["frames.images", "background.image"],
      },
      {
        interaction: "timeline-playback",
        invalidates: ["composite"],
        mustNotInvalidate: ["decode"],
        targets: ["timeline.currentTimeSeconds"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["decode"],
        targets: ["canvas.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["decode"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["export"],
        mustNotInvalidate: ["decode"],
        targets: [
          "export.image.format",
          "export.image.resolution",
          "export.video.format",
          "export.video.resolution",
        ],
      },
    ],
    passes: [
      {
        cacheKey: ["mediaAssets[].dataUrl"],
        id: "decode",
        inputs: ["frames.images", "background.image"],
        invalidatedBy: ["media-import"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["frame.*", "background.*", "timeline.loopProgress", "canvas.renderScale"],
        id: "composite",
        inputs: ["decode"],
        invalidatedBy: [
          "control-drag",
          "control-change",
          "timeline-playback",
          "media-import",
        ],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "main",
      },
      {
        id: "export",
        inputs: ["decode"],
        invalidatedBy: ["export"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Uploaded screenshots are contain-fit; extreme upscaling of small uploads can soften edges at large canvas sizes.",
      "GIF export quantizes to a 256-color palette, so smooth gradients can band in the exported GIF.",
    ],
    layers: [
      {
        content: ["bitmap-media", "composite"],
        exportMode: "composited",
        id: "backdrop",
        kind: "background",
        primitiveCount: "low",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-product-output]",
      },
      {
        content: ["bitmap-media"],
        exportMode: "composited",
        id: "frame",
        kind: "product-foreground",
        primitiveCount: "low",
        renderer: "canvas-2d",
        uiSelector: "[data-toolcraft-product-output]",
      },
    ],
    measuredAlternativeEvidence: [
      {
        alternativeStrategy: "webgl",
        decision:
          "Keep Canvas 2D for preview: the preview draws at most two cached decoded bitmaps plus one fill per frame through GPU-backed drawImage. The only per-pixel stage is the offline GIF export pass, which already reads pixels back through a WebGL texture/framebuffer before CPU palette quantization, so a WebGL preview pipeline would add texture-upload complexity without removing any interactive CPU pixel loop.",
        fixture:
          "1920x1080 uploaded section image, renderScale 2, Scale 100, and Crossfade on the default 1920x1080 canvas.",
        measuredResult:
          "Browser performance checkpoint for preview-render-max-media and timeline-playback-crossfade passed the frame-gap and long-task jank budgets (frame gap <= 120ms, long task <= 200ms) on Canvas 2D with the 1080p stress fixture at renderScale 2.",
        scenarioId: "preview-render-max-media",
      },
    ],
    performanceRisks: [
      "1080p uploaded media at renderScale 2 makes each composite draw the full 3840x2160 backing; decode is cached by dataUrl so draws stay drawImage-only.",
      "Crossfade draws two frames per tick during playback, doubling composite cost at slot boundaries.",
      "GIF export runs a CPU quantization loop per exported frame; it reports frame progress and yields between frames so the UI stays responsive.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "pixel",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "WebGL/WebGPU were evaluated but not chosen: the interactive scene is at most two cached decoded bitmaps plus one fill per frame via GPU-backed drawImage compositing, with no shaders and no dense primitive fields; the measured stress scenarios pass at 1080p media with renderScale 2 on Canvas 2D (see measuredAlternativeEvidence).",
      "DOM/SVG were rejected because the product output is exported raster pixels (PNG, video frames, GIF frames) and needs one pixel-identical draw path for preview and export/copy; there is no text-output or vector-output surface to preserve.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "preview render composites heavy media in one cached pass",
      browser: true,
      browserTestName: "browser perf: preview render stays responsive with 4k section media",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000 },
      expectedObservable:
        "The canvas preview renders the uploaded 1080p section image without long tasks; decode runs once and repeated renders reuse the cached bitmap.",
      fixture: "One 1920x1080 uploaded section image on the default canvas.",
      id: "preview-render-max-media",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason:
          "A 1080p screenshot is the heaviest realistic web-design section upload for social mockups.",
        value: heavyMedia,
      },
      target: "frames.images",
      uiSelector: "[data-toolcraft-product-output]",
      values: { default: { height: 1080, width: 1920 }, max: heavyMedia, min: { height: 240, width: 320 } },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "frame scale changes the drawn frame footprint",
      browser: true,
      browserTestName:
        "browser perf: frame scale drag stays live with 4k media at render scale 2",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Scale",
      expectedObservable:
        "Dragging Scale updates the composed frame live during the drag with a 4K source image at renderScale 2; the backing canvas keeps the selected render scale.",
      fixture: "4K uploaded section image, renderScale 2, Scale dragged to its maximum.",
      id: "frame-scale-drag",
      interaction: "control-drag",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 100,
          metric: "numeric-max",
          smoothTarget: 100,
          smoothTargetRatio: 1,
          target: "frame.scale",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Scale 100% draws the largest frame area and the largest shadow blur region the control allows.",
        value: 100,
      },
      target: "frame.scale",
      values: { default: 70, max: 100, min: 20 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: customLoadProfile("frames.images", {
          renderScale: 2,
          sourceMedia: heavyMedia,
        }),
        reason:
          "The app baseline before the drag is heavy independent state: a 4K uploaded source image and the maximum renderScale 2 backing.",
        value: { renderScale: 2, sourceMedia: heavyMedia },
      },
    },
    {
      automated: true,
      automatedTestName: "corner radius rounds the frame corners",
      browser: true,
      browserTestName: "browser perf: corner radius drag stays live with heavy media",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Corner radius",
      expectedObservable:
        "Dragging Corner radius re-clips and redraws the frame live during the drag with the heavy source image.",
      fixture: "4K uploaded section image with Corner radius dragged to its maximum.",
      id: "corner-radius-drag",
      interaction: "control-drag",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 80,
          metric: "numeric-max",
          smoothTarget: 80,
          smoothTargetRatio: 1,
          target: "frame.cornerRadius",
          userFacingRange: "fully-guaranteed",
        },
        reason: "80px is the largest clip radius the control allows.",
        value: 80,
      },
      target: "frame.cornerRadius",
      values: { default: 16, max: 80, min: 0 },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the drag.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "background blur softens the backdrop image",
      browser: true,
      browserTestName: "browser perf: background blur drag stays live with a heavy backdrop",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Blur",
      expectedObservable:
        "Dragging Blur applies the canvas blur filter to the full-canvas backdrop image live during the drag.",
      fixture: "A 1920x1080 backdrop image in Image mode with Blur dragged to its maximum.",
      id: "background-blur-drag",
      interaction: "control-drag",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 40,
          metric: "numeric-max",
          smoothTarget: 40,
          smoothTargetRatio: 1,
          target: "background.blur",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "40px is the largest blur radius the control allows; canvas blur cost scales with radius over the full backdrop.",
        value: 40,
      },
      target: "background.blur",
      values: { default: 0, max: 40, min: 0 },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: { ...heavyMediaLoadProfile, target: "background.image" },
        reason: "A 1080p backdrop image is the independent heavy baseline for the blur drag.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "transition mode switches between cut and crossfade frame mixing",
      browser: true,
      browserTestName: "browser perf: crossfade transition keeps playback responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Transition",
      expectedObservable:
        "Switching Transition to Crossfade doubles frame draws at slot boundaries without freezing input or playback.",
      fixture: "Two uploaded section images playing on the default timeline.",
      id: "transition-change",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("frames.transition", "crossfade"),
        reason:
          "Crossfade is the heaviest transition: it draws two frames with alpha blending instead of one opaque frame.",
        value: "crossfade",
      },
      target: "frames.transition",
      values: { default: "cut", max: "crossfade", min: "cut" },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the change.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "background mode selects solid gradient or image backdrops",
      browser: true,
      browserTestName: "browser perf: image backdrop mode keeps control changes responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Type",
      expectedObservable:
        "Switching background Type to Image draws the cover/cropped backdrop bitmap each frame without input delay.",
      fixture: "A large backdrop image with one section image on the default canvas.",
      id: "background-mode-change",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("background.mode", "image"),
        reason:
          "Image mode is the heaviest backdrop: it draws a full-canvas cover bitmap on every composite instead of a fill.",
        value: "image",
      },
      target: "background.mode",
      values: { default: "solid", max: "image", min: "solid" },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the change.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "backdrop image covers the canvas behind frames",
      browser: true,
      browserTestName: "browser perf: importing a 4k backdrop image stays within budget",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 250, maxInteractionMs: 2000 },
      controlLabel: "Backdrop image",
      expectedObservable:
        "Importing a 1080p backdrop image decodes once and renders the cover backdrop without blocking the panel.",
      fixture: "A generated 1920x1080 PNG uploaded through the Backdrop image control.",
      id: "background-image-import",
      interaction: "media-import",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          ...heavyMediaLoadProfile,
          target: "background.image",
        },
        reason: "A 1080p backdrop is the heaviest realistic background image for social mockups.",
        value: heavyMedia,
      },
      target: "background.image",
      values: { default: { height: 1080, width: 1920 }, max: heavyMedia, min: { height: 240, width: 320 } },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "frame shadow toggles the drop shadow pass",
      browser: true,
      browserTestName: "browser perf: frame shadow toggle keeps the canvas responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Shadow",
      expectedObservable:
        "Toggling Shadow adds the canvas blur pass behind the frame without freezing the preview.",
      fixture: "One large uploaded section image at maximum Scale.",
      id: "frame-shadow-change",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("frame.shadow", true),
        reason: "Shadow on is the heavier branch: it adds a blurred fill pass per composite.",
        value: true,
      },
      target: "frame.shadow",
      values: { default: true, max: true, min: false },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the change.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "include background controls png alpha and preview background",
      browser: true,
      browserTestName: "browser perf: include background toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable:
        "Toggling Include hides or shows the backdrop layer without input delay or viewport jumps.",
      fixture: "Default canvas with one uploaded section image.",
      id: "include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background color fills the solid backdrop",
      browser: true,
      browserTestName: "browser perf: background color changes stay responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Type",
      expectedObservable:
        "Committing a new background hex updates the backdrop fill without input delay.",
      fixture: "Solid background mode on the default canvas.",
      id: "background-color-change",
      interaction: "control-change",
      target: "background.color",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background gradient renders type angle and stops",
      browser: true,
      browserTestName: "browser perf: gradient edits keep the backdrop responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Type",
      expectedObservable:
        "Editing gradient stops rebuilds one CanvasGradient per draw without input delay.",
      fixture: "Gradient background mode with two stops.",
      id: "background-gradient-change",
      interaction: "control-change",
      target: "background.gradient",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image export format changes the exported mime type",
      browser: true,
      browserTestName: "browser perf: image export format change stays responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable:
        "Switching the image export format updates runtime state without blocking the panel.",
      fixture: "Default canvas with one uploaded section image.",
      id: "image-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "video export format picks a supported recorder mime",
      browser: true,
      browserTestName: "browser perf: video export format change stays responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable:
        "Switching the video export format updates runtime state without blocking the panel.",
      fixture: "Default canvas with one uploaded section image.",
      id: "video-format-change",
      interaction: "control-change",
      target: "export.video.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "section images map to the ordered frame sequence",
      browser: true,
      browserTestName: "browser perf: importing 4k section media stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      controlLabel: "Section images",
      expectedObservable:
        "Importing a 1920x1080 image decodes once, appends a frame, and renders it without blocking the panel.",
      fixture: "A generated 1920x1080 PNG uploaded through the Section images control.",
      id: "media-import-4k",
      interaction: "media-import",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason:
          "1080p screenshots are the heaviest realistic import for social section UI showcases.",
        value: heavyMedia,
      },
      target: "frames.images",
      values: { default: { height: 1080, width: 1920 }, max: heavyMedia, min: { height: 240, width: 320 } },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "image export resolution changes exported pixel dimensions",
      browser: true,
      browserTestName: "browser perf: 8k png export completes within the export budget",
      budget: { maxExportMs: 8000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Export PNG at 8K renders an 8192px long-edge canvas and encodes it without exceeding the export budget.",
      fixture: "One large uploaded section image exported at 8K.",
      id: "export-image-8k",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("export.image.resolution", "8k"),
        reason: "8K is the largest exported pixel count the Image Export control allows.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "video export resolution matches image export quality at current video size",
      browser: true,
      browserTestName: "browser perf: 4k video export completes within the export budget",
      budget: { maxExportMs: 8000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Export Video at 4K records encoder-safe dimensions over the timeline duration within the export budget.",
      fixture: "One uploaded section image exported as 4K video over the 1.5s timeline.",
      id: "export-video-4k",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("export.video.resolution", "4k"),
        reason: "4K is the largest encoded video output the Video Export control allows.",
        value: "4k",
      },
      target: "export.video.resolution",
      values: { default: "current", max: "4k", min: "current" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "timeline loop maps one frame cycle to the edited duration",
      browser: true,
      browserTestName: "browser perf: timeline playback samples frames without jank",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200 },
      expectedObservable:
        "Playback advances the frame cycle at the timeline duration without frame gaps; crossfade boundaries stay smooth.",
      fixture: "Two large section images with Crossfade playing on the default timeline.",
      id: "timeline-playback-crossfade",
      interaction: "timeline-playback",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: customLoadProfile("frames.transition", {
          sourceMedia: heavyMedia,
          transition: "crossfade",
        }),
        reason:
          "Crossfade playback over 4K media draws two large bitmaps per frame at slot boundaries — the heaviest steady-state animation path.",
        value: { sourceMedia: heavyMedia, transition: "crossfade" },
      },
      uiSelector: "[data-toolcraft-product-output]",
      values: {
        default: { sourceMedia: { height: 1080, width: 1920 }, transition: "cut" },
        max: { sourceMedia: heavyMedia, transition: "crossfade" },
        min: { sourceMedia: { height: 240, width: 320 }, transition: "cut" },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "transition mode switches between cut and crossfade frame mixing",
      browser: true,
      browserTestName: "browser perf: dragging the viewport during playback stays smooth",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      expectedObservable:
        "Dragging the canvas viewport while playback runs coalesces animation renders, keeps play state, and resumes at the correct timeline time.",
      fixture: "Two 4K section images playing with Crossfade while the viewport is dragged.",
      id: "animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: customLoadProfile("frames.transition", {
          sourceMedia: heavyMedia,
          transition: "crossfade",
        }),
        reason:
          "Playback plus viewport drag is the combined worst case for animation scheduling with 4K media.",
        value: { sourceMedia: heavyMedia, transition: "crossfade" },
      },
      uiSelector: "[data-toolcraft-product-output]",
      values: {
        default: { sourceMedia: { height: 1080, width: 1920 }, transition: "cut" },
        max: { sourceMedia: heavyMedia, transition: "crossfade" },
        min: { sourceMedia: { height: 240, width: 320 }, transition: "cut" },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "frame scale changes the drawn frame footprint",
      browser: true,
      browserTestName: "browser perf: toolbar zoom under stress keeps frame gaps within budget",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      expectedObservable:
        "Toolbar zoom in/out with the combined heavy state keeps frame gaps within budget and does not jump the viewport.",
      fixture: "4K media, renderScale 2, Scale 100, Crossfade playback while zooming.",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: customLoadProfile("frame.scale", {
          renderScale: 2,
          scale: 100,
          sourceMedia: heavyMedia,
        }),
        reason:
          "Zooming while the heaviest composite state is active is the worst viewport interaction case.",
        value: { renderScale: 2, scale: 100, sourceMedia: heavyMedia },
      },
      uiSelector: "[data-toolcraft-product-output]",
      values: {
        default: { renderScale: 2, scale: 70, sourceMedia: { height: 1080, width: 1920 } },
        max: { renderScale: 2, scale: 100, sourceMedia: heavyMedia },
        min: { renderScale: 1, scale: 20, sourceMedia: { height: 240, width: 320 } },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "canvas keeps editable output size when media uploads",
      browser: true,
      browserTestName: "browser perf: panel interactions keep the canvas viewport stable",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      expectedObservable:
        "Changing controls and scrolling the panel never changes canvas zoom or offset unexpectedly.",
      fixture: "Default canvas with one uploaded section image.",
      id: "viewport-stability",
      interaction: "viewport-stability",
      uiSelector: "[data-toolcraft-product-output]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image export resolution changes exported pixel dimensions",
      browser: true,
      browserTestName: "browser perf: image export resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Selecting a different image export resolution updates runtime state without blocking the panel; export cost is covered by export-image-8k.",
      fixture: "Image Export resolution switched from 4K to 8K.",
      id: "image-resolution-change",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("export.image.resolution", "8k"),
        reason: "8K is the largest exported pixel count the Image Export control allows.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the change.",
        value: heavyMedia,
      },
    },
    {
      automated: true,
      automatedTestName: "video export resolution matches image export quality at current video size",
      browser: true,
      browserTestName: "browser perf: video export resolution change stays responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 200, maxInteractionMs: 2000 },
      controlLabel: "Resolution",
      expectedObservable:
        "Selecting a different video export resolution updates runtime state without blocking the panel; export cost is covered by export-video-4k.",
      fixture: "Video Export resolution switched from Current to 4K.",
      id: "video-resolution-change",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: customLoadProfile("export.video.resolution", "4k"),
        reason: "4K is the largest encoded video output the Video Export control allows.",
        value: "4k",
      },
      target: "export.video.resolution",
      values: { default: "current", max: "4k", min: "current" },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: heavyMediaLoadProfile,
        reason: "A 4K uploaded source image is the independent heavy baseline for the change.",
        value: heavyMedia,
      },
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "frames.transition",
    "frame.scale",
    "frame.cornerRadius",
    "frame.shadow",
    "background.mode",
    "background.blur",
    "export.image.resolution",
    "export.video.resolution",
  ],
});
